title: Open Horizon
description: An Open Source Project for secure and robust containerized application management for constrained devices.
theme: jekyll-theme-tactile
exclude: [docs/nl, vendor]


# Secondary Parameters
header-img: img/hero-dark.jpg
headercolor: "#FFFFFF"
logo: img/logos/open-horizon.png

# Tertiary Parameters
github_username: open-horizon
project_repository: open-horizon.github.io
altmetric: true